/*
 * this is a legacy header code manually written and not relevant to the /inst/include/flowCore.h autogenerated by Rcpp
 * Eventually this file needs to be deprecated and replaced.
 */
#include <R.h>
#include <Rinternals.h>

SEXP biexponential_transform(SEXP input,SEXP A,SEXP B,SEXP C,SEXP D,SEXP F,SEXP G,SEXP tol,SEXP maxit);
SEXP inPolygon(SEXP _data, SEXP _vertices);
SEXP inPolytope(SEXP _data, SEXP _A, SEXP _b);

