# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convertRawBytes <- function(bytes, isInt, colSize, ncol, isBigEndian) {
    .Call('flowCore_convertRawBytes', PACKAGE = 'flowCore', bytes, isInt, colSize, ncol, isBigEndian)
}

fcsTextParse <- function(txt, emptyValue) {
    .Call('flowCore_fcsTextParse', PACKAGE = 'flowCore', txt, emptyValue)
}

uint2double <- function(input, isBigEndian) {
    .Call('flowCore_uint2double', PACKAGE = 'flowCore', input, isBigEndian)
}

